### ISSUE TITLE
Re:Start stuck in (Payon > Prontera > Alberta > Payon > Pront...) loop when moving to Aldebaran

### ISSUE THREAD

**Issue by kipme** [OpenKore/openkore#817] opened 2017-08-01 12:07 UTC
Hello, the bot isn't able to move to Aldebaran without manual help. It gets stuck in a warp loop that goes to Payon > Prontera > Alberta instead of going to Prontera > Geffen > Aldebaran. I can't figure out the reason why.

**Comment by xTriumph** [comment] 2017-08-01 13:06
What is your start point?
I will check it and try to reproduce the bug from prontera.

**Comment by Newbieman1234132** [comment] 2017-08-01 13:11
Anyone can help me in philippine ragnarok online?

**Comment by xTriumph** [comment] 2017-08-01 13:21
@Newbieman Could you create a issue relating your problem? Thanks

**Comment by xTriumph** [comment] 2017-08-01 13:57
@kipme Fixed it. openkore-master>tables>iRO>Restart>portals.txt
change your #Non-Vip Warps to this:

`prontera 146 89 izlude 94 103 2000 c r2 c r0
prontera 146 89 geffen 120 39 2000 c r2 c r1
prontera 146 89 payon 161 58 2000 c r2 c r2
prontera 146 89 morocc 156 47 2000 c r2 c r3
prontera 146 89 alberta 117 56 2000 c r2 c r5
prontera 151 29 izlude 94 103 2000 c r2 c r0
prontera 151 29 geffen 120 39 2000 c r2 c r1
prontera 151 29 payon 161 58 2000 c r2 c r2
prontera 151 29 morocc 156 47 2000 c r2 c r3
prontera 151 29 alberta 117 56 2000 c r2 c r5
prontera 151 29 comodo 209 143 3000 c r2 c r6
prontera 151 29 umbala 100 154 3000 c r2 c r7
prontera 282 200 izlude 94 103 2000 c r2 c r0
prontera 282 200 geffen 120 39 2000 c r2 c r1
prontera 282 200 payon 161 58 2000 c r2 c r2
prontera 282 200 morocc 156 47 2000 c r2 c r3
prontera 282 200 alberta 117 56 2000 c r2 c r5
prontera 282 200 comodo 209 143 3000 c r2 c r6
prontera 282 200 umbala 100 154 3000 c r2 c r7
prontera 29 207 izlude 94 103 2000 c r2 c r0
prontera 29 207 geffen 120 39 2000 c r2 c r1
prontera 29 207 payon 161 58 2000 c r2 c r2
prontera 29 207 morocc 156 47 2000 c r2 c r3
prontera 29 207 alberta 117 56 2000 c r2 c r5
prontera 29 207 comodo 209 143 3000 c r2 c r6
prontera 29 207 umbala 100 154 3000 c r2 c r7
prontera 98 120 yuno 157 167 1800 c c r0 c
geffen 120 62 prontera 116 72 1200 c r2 c r0
geffen 120 62 aldebaran 168 112 1200 c r2 c r1
geffen 120 62 gef_fild10 52 326 1200 c r2 c r2
geffen 120 62 mjolnir_02 99 351 1700 c r2 c r3
geffen 203 123 prontera 116 72 1200 c r2 c r0
geffen 203 123 aldebaran 168 112 1200 c r2 c r1
geffen 203 123 gef_fild10 52 326 1200 c r2 c r2
geffen 203 123 mjolnir_02 99 351 1700 c r2 c r3
aldebaran 143 119 geffen 120 39 2000 c r2 c r0
izlude 134 88 prontera 116 72 2000 c r2 c r0
yuno 152 187 einbroch 67 195 2000 c r2 c r0
yuno 152 187 lighthalzen 159 90 2000 c r2 c r1
yuno 152 187 hugel 98 150 2000 c r2 c r2
yuno 152 187 rachel 119 135 2000 c r2 c r3
yuno 327 108 aldebaran 168 112 2000 c r2 c r0
yuno 142 183 prontera 116 72 1800 c c r0 c n
morocc 156 97 prontera 116 72 2000 c r2 c r0
comodo 195 150 morocc 156 47 2000 c c r2 c r0
payon 181 104 prontera 116 72 2000 c r2 c r0
payon 175 226 prontera 116 72 1200 c r2 c r0
alberta 113 60 payon 161 58 2000 c r2 c r0
rachel 109 138 veins 205 101 2200 c r2 c r0
rachel 109 138 yuno 158 125 3000 c r2 c r1
veins 208 128 rachel 115 125 2200 c r2 c r0
veins 208 128 yuno 158 125 3000 c r2 c r1
moc_para01 14 32 prontera 116 72 1800 c c r0 c n`

The problem was in the warp that dosent exists in this server yet, originaly there is a warp to aldebaran on resp 5 in the prontera kafra, but in this server the warp 5 goes to alberta, and alberta does not have a warp to prontera, so the bot warps to payon and then in payon it goes for prontera. Then the loop happens.

**Comment by idrhnbot2** [comment] 2017-08-01 16:51
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602

**Comment by idrhnbot3** [comment] 2017-08-02 04:16
Beli Zeny Mahal? Jasa Joki Bayar mahal cuman dpt 1ID?

Mending ngebot ajah gan bisa stock zeny sendiri bahkan jualan zeny sendiri, bisa bikin 100ID++ lvl 99 dalam waktu singkat dan langsung banyak ID. Cuman di www.rhanfelta.blogspot.com ayo gabung gan udah banyak bukti dan testi dari yang udah gabung

Contact: 081380644602

**Comment by idrhnbot3** [comment] 2017-08-02 04:16
Beli Zeny Mahal? Jasa Joki Bayar mahal cuman dpt 1ID?

Mending ngebot ajah gan bisa stock zeny sendiri bahkan jualan zeny sendiri, bisa bikin 100ID++ lvl 99 dalam waktu singkat dan langsung banyak ID. Cuman di www.rhanfelta.blogspot.com ayo gabung gan udah banyak bukti dan testi dari yang udah gabung

Contact: 081380644602

**Comment by kipme** [comment] 2017-08-02 05:36
Thanks a lot @xTriumph! Works perfectly. Have a great day!

**Comment by kipme** [comment] 2017-08-02 14:40
Can we make this a pull request?

**Comment by xTriumph** [comment] 2017-08-02 18:16
@kipme i've done it, its merged now.
 @Henrybk has a new pull that fixes more portals, but it needs to be aproved.

**Comment by alisonrag** [comment] 2017-08-03 15:30
fixed in #822

**Closed** 2017-08-04 16:29 UTC
