### ISSUE TITLE
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16

### ISSUE THREAD

**Issue by NandoPrates** [OpenKore/openkore#1340] opened 2017-10-30 14:29 UTC
on ubuntu 17.10
```
Connecting to Account Server...
Connecting (128.241.92.133:6800)... connected
---------- Account Info ----------

----------------------------------
---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Odin                  3961   128.241.92.138  4500
-----------------------------------------------------
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16 at /usr/lib/x86_64-linux-gnu/perl/5.22/Socket.pm line 153.
Closing connection to Account Server
```

**Comment by NandoPrates** [comment] 2017-11-04 15:49
is https://msdn.microsoft.com/en-us/commandline/wsl/install-win10?f=255&MSPPError=-2147217396
ubuntu on win 10 .-.

**Comment by asiphm** [comment] 2018-01-05 10:02
Tested with the same environment WSL Ubuntu resulting the same :

---------------------- Servers ----------------------
#   Name                  Users  IP              Port
0   Thor                  412    128.241.92.155  4500
1   Chaos                 1644   128.241.92.130  4500
-----------------------------------------------------
Closing connection to Account Server
Bad arg length for Socket::unpack_sockaddr_in, length is 4096, should be 16 at /usr/lib/x86_64-linux-gnu/perl/5.22/Socket.pm line 153.

**Comment by moneyisgod** [comment] 2018-07-18 20:57
Maybe the problem is not with ubuntu, and with perl 5.22 ?!

**Comment by alisonrag** [comment] 2021-02-27 17:33
there is a very long time since this issue started, but seems until today this issue is not fixed at WSL
https://github.com/microsoft/WSL/issues/134

**Comment by alisonrag** [comment] 2021-02-28 01:11
Its not related to openkore

**Closed by alisonrag** 2021-02-28 01:11 UTC
Labels: server: iRO Re:start
