### ISSUE TITLE
Inventory list messy / a bit bugged

### ISSUE THREAD

**Issue by Muramas** [OpenKore/openkore#2937] opened 2019-10-10 18:36 UTC
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: OpenKore what-will-become-2.1 ( version git:0605143_2019-10-04 ctime:2019_10_07 )

* **Server**: iRO

* **Bug Report / Feature Request**: Feature Request

* **Summary**: The i screen gives a perfect summary of your items I would hope to have something on the wx inventory screen that does the same functionality.

-1 The list often states that certain items are equipped on you which are not (like fluff being equipped)
-2 Items are not sorted in any meaningful way (Sort by usable, equipped, equipment)

**Comment by Shmerrick** [comment] 2019-11-26 07:02
I'm experiencing the same thing. I think issue #2983 covers the same thing. I've also noticed that autobuy is not working as intended either. The bot will buy the item, but it thinks that it doesn't have the item in the inventory.

**Comment by Nipodemos** [comment] 2019-11-26 15:06
@Muramas ash shmerrick said, this issue was already been reported on #2983 
i'm gonna close this to avoid duplicated issues

**Comment by alisonrag** [comment] 2019-11-26 17:03
this issue is related to wxstart inventory/storage/cart view

the wxstart page view dont sort the items, only show as openkore receive

he is asking if is possible to sort by type

screen:
![image](https://user-images.githubusercontent.com/10372732/69655542-8520b800-1055-11ea-9793-4d099e0567dd.png)

**Comment by Muramas** [comment] 2019-11-26 17:21
> this issue is related to wxstart inventory/storage/cart view
> 
> the wxstart page view dont sort the items, only show as openkore receive
> 
> he is asking if is possible to sort by type
> 

 Thanks, was going to say that it was closed out of scope.

**Comment by Nipodemos** [comment] 2019-11-26 17:22
sorry for the misunderstanding 😅

**Comment by alisonrag** [comment] 2019-11-26 17:49
> > this issue is related to wxstart inventory/storage/cart view
> > the wxstart page view dont sort the items, only show as openkore receive
> > he is asking if is possible to sort by type
> 
> Thanks, was going to say that it was closed out of scope.

im working in this, but it touch a lot of code, im trying to make it simple

**Comment by alisonrag** [comment] 2023-02-07 18:25
this function interact direct with $char->inventory->getItems
it return a reference to array that contains objects, we cant change this, because this apply to other lists like cart and storage

**Closed by alisonrag** 2023-02-07 18:25 UTC
