### ISSUE TITLE
Poseidon.pl is not answering game guard request

### ISSUE THREAD

**Issue by flacrasec** [OpenKore/openkore#1054] opened 2017-09-02 03:05 UTC
Please refer to the following resources for help using OpenKore:
 faqs - http://openkore.com/index.php/Frequently_Asked_Questions (such as "Packet Tokenizer")
 forum - http://forums.openkore.com
 documentation wiki - http://openkore.com/index.php/Main_Page

* Before submitting an issue, ensure you are on the latest release
I'am always here and update my openkore everyday
* Check if an issue already exists for your request
* Please post in English if possible

###### Summary: 
Poseidon server is not answering game guard requests and causing disconnection.
###### Affected configuration(s)/ file(s):
openkore/src/poseidon/poseidon.pl maybe more files but I'm not sure which they are.
```Include relevant code snippets and source code references```
###### Expected Behavior:
instead of the changing numbers o ragnarok client 5 6 7 6 7 it is expected that only one number appears 6 6 6 6
###### Actual Behavior:
![image](https://user-images.githubusercontent.com/17572686/29992423-29c2558e-8f71-11e7-8c2c-29ae21996abb.png)
###### Steps to Reproduce:
Just open poseidon and openkore at bRO server and it occurs some times.
###### Affected configuration(s)/ file(s):
```Include relevant code snippets and source code references```
###### Drawbacks:
it is impossible to play at bRO server when this issue occurs since the time request of game guard is about 30 seconds and a disconnection if not answered, and them with too many disconnections our account password is reseted by Level Up Games1 aka. LUG

**Comment by lututui** [comment] 2017-09-02 14:18
This happens when CPU hovers around 100%

**Comment by flacrasec** [comment] 2017-09-02 22:58
Unfortunately, it was occuring everytime with me, even with just 1 account, but I did some changes at my own, and was wanting to insert this as issue. because it is not all time with 100% of CPU sometimes any unstability lead to this issue. If there is something I can do to improve a fix for it let me know and I will try to achieve more information with this since it is occuring everytime.

**Comment by vasa1983** [comment] 2017-12-06 16:35
i've met the same issue when running openkore on cRO.

**Comment by Nipodemos** [comment] 2019-09-10 10:44
closing this since the problem is caused by CPU at 100% of use, which i believe we can't do much to solve.
Plase reopen if you think differently

**Closed by Nipodemos** 2019-09-10 10:44 UTC
