### ISSUE TITLE
Openkore disconnection when bot goes to another map.

### ISSUE THREAD

**Issue by jepejepe** [OpenKore/openkore#993] opened 2017-08-24 12:55 UTC
I noticed that some of my bots whenever they "accidentally" step on another map portal due to chasing their targets gets disconnected. I was wondering if this is still unfixed or what. The version of openkore that I'm using right now is from last weekend.

Also, I noticed that wxstart crashes from time to time. I don't know if this is because I'm running multiple bots at the same time or not.

**Comment by jepejepe** [comment] 2017-08-24 12:55
![a](https://user-images.githubusercontent.com/31201253/29667343-97090908-890e-11e7-9d83-0f6eb2682c83.PNG)

Here's a screenshot.

**Comment by ChrstphrR** [comment] 2017-08-24 14:03
A)  The template suggests before posting that you check with a more recent version of Openkore, yet you use is from "last weekend".    You should report the version you're using, if you're going to stick with an old one, and ... most everyone that will pitch in to help will suggest you update to the latest to test.

B) But, before you update, you may want to correct one of the causes of the jumping into the portal:
your config.txt value for attackMinPortalDistance -- which may not be configured, so you're relying on the default value of 4.   I checked the code to ensure the wiki entry wasn't out of whack - it is a 4 tile avoidance of the portals, which might not be adequate for the map you're on.

http://openkore.com/index.php/AttackMinPortalDistance

So, first, try checking if you have that distance configured with your bot(s), and see if the problem reoccurs.  And if it's still an issue, you might well want to consider jumping up to a more current commit to see if the disconnect is still an issue.

And, please post what steps provide a solution to any fix that works for you, so others can learn from it too.   If moving to a more recent version of Openkore was the fix, please, please post the "version" string in your post.

**Comment by brylle0714** [comment] 2017-08-24 14:46
same problem when entering portal bot disconnect and when using flywing bot disconnect! is there any fix for this. thanks

**Comment by jepejepe** [comment] 2017-08-24 15:21
@ChrstphrR noted will try this out when I get home thank you

**Comment by ChrstphrR** [comment] 2017-08-24 16:00
@brylle0714  You didn't state which version of openkore you're using, so that is the first step you should be taking.  

Also, you're piggybacking on another issue on this one., so if you have problem that don't resolve with updating Openkore, **open a new issue** and **carefully document what you tested out**, what version string your copy of Openkore is (cut and paste it in).  Thank you.

**Closed** 2017-08-24 19:35 UTC
Labels: help wanted, needs to be tested
