### ISSUE TITLE
bug report iro

### ISSUE THREAD

**Issue by Sabog29** [OpenKore/openkore#445] opened 2017-02-18 09:29 UTC
hi need help. how to fix this

OpenKore version what-will-become-2.1
Network state = 3
Network handler = Network::DirectConnection
SVN revision: 8954
Loaded plugins:
  plugins/macro/macro.pl (macro; description: allows usage of macros)

Error message:
Unknown charBlockSize: 145 at src/Network/Receive.pm line 346.

Stack trace:
Unknown charBlockSize: 145 at src/Network/Receive.pm line 346.
 at src/Network/Receive.pm line 346
	Network::Receive::received_characters_unpackString('Network::Receive::iRO=HASH(0x5d99424)') called at src/Network/Receive/ServerType0.pm line 3007
	Network::Receive::ServerType0::received_characters('Network::Receive::iRO=HASH(0x5d99424)', 'HASH(0x61eac0c)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::iRO=HASH(0x5d99424)', '\x{9d}\x{9}\x{b7}\x{1}\x{9c}x\x{88}\x{0}\x{ec}\x{4}0\x{1}\x{c}4\x{1}\x{0}\x{bf}\x{de}\x{3}\x{0}2\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{8}\x{0}fC\x{0}\x{0}fC\x{0}\x{0}\x{9c}\x{e}\x{9c}\x{e}\x{96}\x{0}\x{dd}...', 'Network::Receive::iRO=HASH(0x5d99424)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::iRO=HASH(0x5d99424)', '\x{9d}\x{9}\x{b7}\x{1}\x{9c}x\x{88}\x{0}\x{ec}\x{4}0\x{1}\x{c}4\x{1}\x{0}\x{bf}\x{de}\x{3}\x{0}2\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{8}\x{0}fC\x{0}\x{0}fC\x{0}\x{0}\x{9c}\x{e}\x{9c}\x{e}\x{96}\x{0}\x{dd}...', 'Network::Receive::iRO=HASH(0x5d99424)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::iRO=HASH(0x5d99424)', 'Network::MessageTokenizer=HASH(0x3940b24)', 'Network::Receive::iRO=HASH(0x5d99424)') called at src/functions.pl line 738
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x4891624)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		return 'a4 V9 v17 Z24 C6 v' if $_ == 106 || !$_;
* 		die "Unknown charBlockSize: $_";
  	}

**Comment by ChrstphrR** [comment] 2017-02-18 11:21
> OpenKore version what-will-become-2.1
> SVN revision: 8954

Looks like a VERY old version you are using.

You're also lacking details that would help in a general situation:
- Server you're on
- Steps to reproduce

Luckily, this does look like you're on a server, like iRO, that recently added episode 14.4 (Doram characters and maps).

IF this is the case, update openkore using the latest code on github, because allanon added a bunch of fixes that allow openkore to log in.

If simply updating doesn't fix this, help us help you, by giving us more details, and not just a paste.

**Comment by Sabog29** [comment] 2017-02-19 12:43
Hi this is the error now.
cart and kafra error

OpenKore version what-will-become-2.1
Network state = 5
Network handler = Network::DirectConnection
SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Can't locate object method "cart" via package "Actor::You" at src/Network/Receive.pm line 1943.

Stack trace:
Can't locate object method "cart" via package "Actor::You" at src/Network/Receive.pm line 1943.
 at src/Network/Receive.pm line 1943
	Network::Receive::actor_status_active('Network::Receive::iRO=HASH(0x5c82d74)', 'HASH(0x61d19e4)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::iRO=HASH(0x5c82d74)', '\x{84}\x{9}\x{be}\x{83}L\x{0}\x{a1}\x{2}\x{f}\'\x{0}\x{0}\x{f}\'\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}', 'Network::Receive::iRO=HASH(0x5c82d74)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::iRO=HASH(0x5c82d74)', '\x{84}\x{9}\x{be}\x{83}L\x{0}\x{a1}\x{2}\x{f}\'\x{0}\x{0}\x{f}\'\x{0}\x{0}\x{1}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}', 'Network::Receive::iRO=HASH(0x5c82d74)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::iRO=HASH(0x5c82d74)', 'Network::MessageTokenizer=HASH(0x3907014)', 'Network::Receive::iRO=HASH(0x5c82d74)') called at src/functions.pl line 738
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x46e4a04)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  	my $status = defined $statusHandle{$type} ? $statusHandle{$type} : "UNKNOWN_STATUS_$type";
* 	$char->cart->changeType($unknown1) if ($type == 673 && defined $unknown1 && ($ID eq $accountID)); # for Cart active
  	$args->{skillName} = defined $statusName{$status} ? $statusName{$status} : $status;

--------------------------------------------------------------------------------------------------------------

SVN revision: unknown
Loaded plugins:
  plugins/breakTime/breakTime.pl (breakTime; description: Automatically disconnect and reconnect at certain times of the day)
  plugins/macro/macro.pl (macro; description: allows usage of macros)
  plugins/profiles/profiles.pl (profiles; description: Profiles Selector)

Error message:
Can't locate object method "storage" via package "Actor::You" at src/Network/Receive.pm line 2427.

Stack trace:
Can't locate object method "storage" via package "Actor::You" at src/Network/Receive.pm line 2427.
 at src/Network/Receive.pm line 2427
	Network::Receive::__ANON__('HASH(0x62050bc)') called at src/Network/Receive/ServerType0.pm line 1097
	Network::Receive::ServerType0::_items_list('Network::Receive::iRO=HASH(0x5c4bc6c)', 'HASH(0x6210a44)') called at src/Network/Receive.pm line 2434
	Network::Receive::storage_items_stackable('Network::Receive::iRO=HASH(0x5c4bc6c)', 'HASH(0x61ef64c)') called at src/Network/PacketParser.pm line 267
	Network::PacketParser::parse('Network::Receive::iRO=HASH(0x5c4bc6c)', '\x{95}\x{9}<\x{1}yggdrasil storage\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{2}\x{0}#\x{2}\x{0}\x{f}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{1}\x{4}\x{0}\x{e8}\x{18}\x{3}\x{90}\x{1}\x{0}\x{0}...', 'Network::Receive::iRO=HASH(0x5c4bc6c)') called at src/Network/Receive.pm line 137
	Network::Receive::parse('Network::Receive::iRO=HASH(0x5c4bc6c)', '\x{95}\x{9}<\x{1}yggdrasil storage\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{2}\x{0}#\x{2}\x{0}\x{f}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{0}\x{1}\x{4}\x{0}\x{e8}\x{18}\x{3}\x{90}\x{1}\x{0}\x{0}...', 'Network::Receive::iRO=HASH(0x5c4bc6c)') called at src/Network/PacketParser.pm line 401
	Network::PacketParser::process('Network::Receive::iRO=HASH(0x5c4bc6c)', 'Network::MessageTokenizer=HASH(0x3907134)', 'Network::Receive::iRO=HASH(0x5c4bc6c)') called at src/functions.pl line 738
	main::mainLoop_initialized() called at src/functions.pl line 75
	main::mainLoop() called at src/Interface.pm line 75
	Interface::mainLoop('Interface::Console::Win32=HASH(0x456ab8c)') called at openkore.pl line 97
	main::__start() called at start.pl line 136

Died at this line:
  		items => [$self->parse_items_stackable($args)],
* 		getter => sub { $char->storage->getByServerIndex($_[0]{index}) },
  		adder => sub { $char->storage->add($_[0]) },

**Comment by allanon** [comment] 2017-03-05 03:03
This is fixed by pull request #440 .

**Closed** 2017-03-08 16:51 UTC
