### ISSUE TITLE
Odd equipauto behavior.

### ISSUE THREAD

**Issue by Dalamar6** [OpenKore/openkore#812] opened 2017-07-31 02:02 UTC
It either goes nuts weapon swapping when mobbed, or, if I use NotMonsters to try to stabilize it, it won't use the stunner [2] vs the target that it should be.

equipAuto {
	topHead
	midHead
	lowHead
	leftHand
	rightHand +5 Stunner [***snip***]
	leftAccessory
	rightAccessory
	robe
	armor
	shoes
	arrow
	monsters Whisper, Marionette, Nightmare, Ghostring, Dragon Tail, Parasite, Hunter Fly
	notMonsters
	monstersCount
	weight 0
	whileSitting 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

equipAuto {
	topHead
	midHead
	lowHead
	leftHand
	rightHand +7 Bible [Desert Wolf*2] [2]
	leftAccessory
	rightAccessory
	robe
	armor
	shoes
	arrow
	monsters Brilight, Cramp, Rideword
	notMonsters
	monstersCount
	weight 0
	whileSitting 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

equipAuto {
	topHead
	midHead
	lowHead
	leftHand
	rightHand +5 Stunner [Metaller:Skel Worker] [2]
	leftAccessory
	rightAccessory
	robe
	armor
	shoes
	arrow
	monsters Injustice, Zealotus, Arclouze, Axe Kobold, Mace Kobold, Sky Petite, Earth Petite, Bathory, Jakk, Carat, Skel Prisoner, Zombie Prisoner, Hammer Kobold
	notMonsters 
	monstersCount
	weight 0
	whileSitting 0
	hp
	sp
	homunculus_hp
	homunculus_sp
	homunculus_dead
	onAction
	whenStatusActive
	whenStatusInactive
	whenFollowing
	spirit
	amuletType
	aggressives
	stopWhenHit 0
	inLockOnly 0
	notWhileSitting 0
	notInTown 0
	timeout 0
	disabled 0
	inInventory
	manualAI 0
}

**Comment by rhnbotfelt11** [comment] 2017-07-31 03:11
pusing mau ngebot? Beli Zeny Mahal? Jasa joki juga mahal? mending ngebot sendiri aman bisa gb 100id ++ sampe lvl 99 bisa ngumpulin zeny cepat bahakan bisa jualan zeny.

Jual BOT Ragnarok Hanya 300Ribu berminat hubungi:081380644602 Mumpung harga promo

https://www.youtube.com/watch?v=8xLIUQH3mKM

**Comment by Aiyaful** [comment] 2017-07-31 14:27
I don't know how to create a macro but this is your prob. First think of you playing it and you got mob, 2 types is okay but what if you got mob by 4 types? HunterFly Whisper Zombie Prison Zealotus? Remember kore will go to aggressive first and they are all, 2nd who hit. Your agi will drop because agi will get negative if you got mob they will eventually hit you so it will get your kore confuse who will hit. Try lessen your monster or use only 1 type of weapon. You do good work trying to think your kore what to use if you got monster, try thinking of something like who you will go to kill first if you got mobs.

**Comment by idrhnbot1** [comment] 2017-08-01 06:14
Ayoo gan promo tinggal untuk 1 orang lagi sudah ada yg order 

Bukti pembelian promo kemarin:
https://image.ibb.co/b3buzk/IMAG0170.jpg

BOT Ragnarok No Limit No HWID bisa ngebot 100 ID++ dalam 1PC bisa di pakai PC laptop warnet tanpa batas.

Dari pada beli Zeny mending jualan Zeny,Dari pada Bayar jasa Joki Mahal Mending Joki pakai BOT bisa bikin lvl 99 100ID++ tanpa bayar joki

berminat hubungi:
081380644602

www.rhanfelta.blogspot.com

**Comment by idrhnbot2** [comment] 2017-08-01 16:51
Ayoo Gan udah 2 Orang ambil promo di rhanfelta dan udah banyak yg lainya beli di rhanfelta sejak febuari
2017 Cek di blog ane gan untuk liat bukti pembelian lainya.

https://preview.ibb.co/n1FYAQ/DSC_0079.jpg

Beli Zeny Mahal? Jasa Joki Mahal? mending order bot di rhanfelta ajah
BOT Gravindo Ready bisa support multi BOT bisa ngebot 100id++ dalam 1PC bisa bikin lvl 99 100ID tanpa bayar joki mahal
cuman dapet 1 char, bisa jualan zeny juga lagi gak perlu beli zeny sama orang bisa stock zeny sendiri

cepetan gan cek di www.rhanfelta.blogspot.com mumpung masih ada promo untuk 1 pemebeli lagi.

Contact: 081380644602

**Comment by Fadreus** [comment] 2019-10-26 06:41
Old stuff..
No feedback..
Not a bug..
Just wrong config..
He got the wrong impression on condition monster works.

He should use switchAuto instead of equipAuto.
Demand closing.

**Closed** 2019-10-26 17:56 UTC
