### ISSUE TITLE
Xkore2 = character error

### ISSUE THREAD

**Issue by Zexeta** [OpenKore/openkore#695] opened 2017-07-15 06:34 UTC
When using xkore 2 im getting character size errors.  I tried different server versions and charactersizes but the best i could get is it to show a character of the opposite sex then disconnect soon as i selected it.  Did anyone get this to actually work yet?

**Comment by kaliwanagan** [comment] 2017-07-15 08:51
would be nice if you finally realize the ro server you're playing at isn't the only ro server out there :)

**Comment by Zexeta** [comment] 2017-07-15 09:08
Fair enough, its iRO Odin, the new Re:start server.  I have never had trouble getting xkore 2 working on other servers.  I dont think the charblocksize n such people are giving out is actually correct?

**Comment by kaliwanagan** [comment] 2017-07-15 10:43
Here's what you can do while someone who has an account in iRO Odin can help.

Download wireshark and capture packets coming and going. Follow the TCP conversation. Check the packet that comes with your character and count number of bytes it has.

You can do a cross check by setting debug on your config.txt so you can see the communication in openkore, which will help you highlight the corresponding packets in wireshark.

**Comment by Slipxxliose** [comment] 2017-07-17 02:57
Just to abreviate, xkore works good in official. bad in privates. sub that reads charBlockSize does the wrong interpretation

**Comment by Zexeta** [comment] 2017-07-21 03:47
@kaliwanagan Is there a way i can private message you the packets?

**Comment by kaliwanagan** [comment] 2017-07-21 07:07
better if you can do it yourself. then you don't have to depend on others to do it for you when you need them updated :)

**Comment by Zexeta** [comment] 2017-07-21 07:10
Well i did do it and im getting 149 charblocksize which obviously didn't work so i apparently did something wrong.  When i login with 147 charblocksize the char shows up the wrong gender and its location is unknown.  It then disconnects soon as i try to load in.

**Comment by kaliwanagan** [comment] 2017-07-21 07:17
try 145?

**Comment by Zexeta** [comment] 2017-07-21 07:24
Sorry i meant 145 in the last post where i said 147.  
145 = wrong sex, unknown location and disconnect
147 = char block error and can't even see the character.

**Comment by Zexeta** [comment] 2017-07-21 20:41
Anyone have any suggestions on this?  xkore1 is a laggy mess and causes my bot to die constantly zzzzzzz.

**Comment by kaliwanagan** [comment] 2017-07-22 03:49
See if using power shell instead of double clicking start.exe will help.

Click on start, type powershell, then drag start.exe from openkore inside the powershell window, then press enter,

That should alleviate some if the lag (just a little bit)

**Comment by kaliwanagan** [comment] 2017-07-22 09:51
So i created an account in iRO and it doesn't looks like a simple charBlockSize issue.

For now, xKore 1 and xKore 0 work properly; xKore 2 correctly connects to the server but isn't proxying the client properly.

**Comment by kaliwanagan** [comment] 2017-07-22 09:56
So while xKore 2 doesn't work, xKore 3 (aka proxy) works.

This combines the features of both 1 and 2 where
* the RO client can drive most of the interaction (xKore 1)
* kore sends packets directly to the server (xKore 2)

This should give better performance than xKore 1. Try it out.

**Comment by Zexeta** [comment] 2017-07-23 18:44
Yeah i am using 3 and its a bit better now.  I just miss being able to run 4 or 5 bots then if someone screws with one of them or there is a problem i can open up the correct shortcut, login to the character through the client solve the problem and close the game again.  Now i have to have the game open for each bot 100% of the time if i want to be able to do this sort of thing.

**Comment by kaliwanagan** [comment] 2017-07-24 04:05
We'll look into it; it's a valid issue report but there really are very few devs right now that are free to help out. So no promises nor guarantees :(

**Comment by moneyisgod** [comment] 2017-07-24 04:11
Hi sir. I will try to perform some look at this. I was suffering about this too. 
I will take a look in a 2013 server, and download 2014/2015 serve and test it.

**Comment by kaliwanagan** [comment] 2017-07-24 07:59
This is iRO restart. I can confirm the disconnection happens there after char server login.

I just fixed an issue with XKore 3 as well, it might be related.

**Comment by moneyisgod** [comment] 2017-07-24 08:12
Okay now the thing is come out. Since we have too a bug in 2013-15 servers using XKore2. I'll left this iRO problem to other. 'cause i can't test it. But for private i'll try to solve.

**Comment by kaliwanagan** [comment] 2017-07-24 17:18
#375 enabled some assertions added by EternalHarvest and it seems we have the culprits (ss by @Henrybk )
https://i.gyazo.com/0a522b5744d8ed512c023447b097a6fa.png

```
17:12 < Henrybk> lastLoginIP and lastLoginTime are not defined
17:12 < Henrybk> by default
```

**Comment by Zexeta** [comment] 2017-07-24 18:47
Hmm my kore never crashed like that when testing it.  My client simply says disconnected after i try to select the character(wrong gender and unknown locaiton) and the bot itself continues running fine.

**Comment by phamtrong204** [comment] 2017-08-03 23:55
My case is same with @Zexeta, but my client show correct gender (unknown location)

**Comment by tlinkin** [comment] 2017-08-27 10:17
bump :) sameas @Zexeta  and @phamtrong204.

Wrong gender and unknown location, then disconnect at char select screen.

**Comment by japs28** [comment] 2017-09-11 13:50
My Girl account works well in xkore 2, but my Boy account got wrong gender and unknown location. IRO re:start

**Comment by icewafu05** [comment] 2017-09-14 21:29
@japs28  hi! how you manage to work xkore 2 on iRO Restart? please help.

**Comment by alisonrag** [comment] 2017-10-12 20:49
working in this:
![char-server-xkore2-iro-restart](https://user-images.githubusercontent.com/10372732/31518370-684cb398-af75-11e7-8970-f90d86bca0d7.png)
![map-server-xkore2-iro-restart](https://user-images.githubusercontent.com/10372732/31518375-6b62e4c6-af75-11e7-9393-45b468cfdb5e.png)

think about the best way to implement this in openkore, because this can be used by some private servers

**Comment by c4c1n6kr3m1** [comment] 2017-10-13 06:45
Don't forget to add ".gat" to map :)

**Comment by Naozumi2k** [comment] 2017-10-22 11:55
Any progress on that? 
Unknown area can be fixed by adding ".gat" to $field->baseName in **src/Base/Ragnarok/CharServer.pm**

**Comment by alisonrag** [comment] 2017-10-22 13:02
@Naozumi2k 
#1287

**Comment by alisonrag** [comment] 2017-10-25 17:29
fixed in #1287

**Closed by alisonrag** 2017-10-25 17:29 UTC
Labels: bug, help wanted, priority: high, server: iRO, server: iRO Re:start

**Comment by jonlejonle** [comment] 2018-02-13 05:18
How to fix it?
![image](https://user-images.githubusercontent.com/36431398/36134494-2086e374-10c0-11e8-88cc-014a0be74d3f.png)
I already change the XKore 0 to Xkore 1 see below
![image](https://user-images.githubusercontent.com/36431398/36134501-29808b7e-10c0-11e8-942d-c77347ad6904.png)
And I run the ragnarok see below
![image](https://user-images.githubusercontent.com/36431398/36134467-fc68a7f2-10bf-11e8-93e4-fe679743240c.png)
Please help me

**Comment by alisonrag** [comment] 2018-02-13 11:37
@jonlejonle 
if openkore cant connect in xkore 0 your setting are wrong

**Comment by jonlejonle** [comment] 2018-02-14 00:25
how to fix the correct setting, where am i to go to check setting

**Comment by jonlejonle** [comment] 2018-02-14 00:26
where to i find the setting to correct it
