### ISSUE TITLE
[pserver]xkore2 already connect to server, but client shows character in delete proces

### ISSUE THREAD

**Issue by tenn0634** [OpenKore/openkore#2028] opened 2018-06-01 15:02 UTC
xkore0\3 works fine , but the xkore 12 , have different issue , 
xkore 1 ,maybe the client was encrypt (pass T-T) , 
xkore 2 ,openkore can login to the server no problem ,but when the client connected to the xkore2 , shows the character in delete proces   ,also wrong gender(suppose to be male) and unknown location .

here is the client.exe :https://drive.google.com/open?id=1qCm66tfGj9-fDf5PP34QCA5uKwX5M5Te
!

**Comment by tenn0634** [comment] 2018-06-01 15:04
![image](https://user-images.githubusercontent.com/16094200/40847881-21925548-65f0-11e8-889b-0f7fcb161e2e.png)

**Comment by alisonrag** [comment] 2018-06-09 22:40
this is caused by wrong charblocksize, can you send the server website to test?

**Comment by tenn0634** [comment] 2018-06-10 09:01
https://drive.google.com/open?id=1MfvznFYoHzkdwRhAfOwRJlr2S2Rzp0Ye , here is the patch for the server .
[servers.txt](https://github.com/OpenKore/openkore/files/2087658/servers.txt)
,if you need to register a account to test  ,  
![reg](https://user-images.githubusercontent.com/16094200/41200038-db9282ca-6ccf-11e8-9a91-467945e54b32.gif) ,

**Comment by alisonrag** [comment] 2018-06-11 14:44
your clientfile and grf is broken '-'

can you send me the website link?

**Comment by tenn0634** [comment] 2018-06-12 12:35
qs-ro.com , it's a forum , seems like grf is encryption ..

**Comment by alisonrag** [comment] 2018-06-20 20:51
C:\Users\ads\Desktop\openkore\src\Network\Receive\kRO\RagexeRE_2016_02_03a.pm
`sub new {
		my ($class) = @_;
	my $self = $class->SUPER::new(@_);
	my %packets = (
		# TODO: character_creation_successful should be the same as char_block
		'006D' => ['character_creation_successful', 'a4 V9 v V2 v14 Z24 C6 CC x2 Z16 x16 C', [qw(charID exp zeny exp_job lv_job opt1 opt2 option stance manner points_free hp hp_max sp sp_max walk_speed jobID hair_style weapon lv points_skill lowhead shield tophead midhead hair_color clothes_color name str agi vit int dex luk slot renameflag mapName sex)]],
		'0097' => ['private_message', 'v Z24 V Z*', [qw(len privMsgUser flag privMsg)]], # -1
		'082D' => ['received_characters_info', 'x2 C5 x20', [qw(normal_slot premium_slot billing_slot producible_slot valid_slot)]],
		'099D' => ['received_characters', 'x2 a*', [qw(charInfo)]],
	);

	foreach my $switch (keys %packets) {
		$self->{packet_list}{$switch} = $packets{$switch};
	}
	
	my %handlers = qw(
		received_characters 099D
		received_characters_info 082D
		sync_received_characters 09A0
	);

	$self->{packet_lut}{$_} = $handlers{$_} for keys %handlers;

	return $self;
}`

all devs

we need to find the first servertype that use 099D as handler and update

**Comment by sctnightcore** [comment] 2018-06-20 21:28
Close my eye.

**Comment by alisonrag** [comment] 2018-08-26 00:45
fixed in #2291

**Closed by alisonrag** 2018-08-26 00:45 UTC
Labels: help wanted, server: Private

**Comment by poweruser13** [comment] 2018-12-11 04:03
@alisonrag Hello can you help me more about this? I have the same issue. I tried your fixes but i get hang on the character server.
First Problem: I have the same problem with this topic (Character Delete in xkore2 char server)
Second Problem: I tried your fixes i replace what's written in my .pm files with your fixes but the problem is it gets hang in the character server.
i'll wait for your reply @alisonrag  thank you !

**Comment by thebeaterkirito** [comment] 2018-12-11 04:05
@alisonrag  Hello can you help me more about this? I have the same issue. I tried your fixes but i get hang on the character server.
First Problem: I have the same problem with this topic (Character Delete in xkore2 char server)
Second Problem: I tried your fixes i replace what's written in my .pm files with your fixes but the problem is it gets hang in the character server.
i'll wait for your reply @alisonrag   thank you !
