### ISSUE TITLE
twRO CdClient Shield

### ISSUE THREAD

**Issue by alisonrag** [OpenKore/openkore#1861] opened 2018-03-16 18:01 UTC
this issue will be used to share infos that can help developers and other peoples about cdclient

###### Summary:
if someone have info about cdclient please share here

###### Affected configuration(s)/ file(s):
connection files to the servers

###### Additional Details:
post calling for help will be deleted

**Comment by alisonrag** [comment] 2018-03-16 18:02
here i will list all issues related to cdclient.

**Comment by sctnightcore** [comment] 2018-03-16 19:06
only kRO:zero use it .

**Comment by kou90258** [comment] 2018-03-17 06:43
#709  Inside CDClient.DLL & Ragexe   ZeusXavier commented on 18 Jul 2017

**Comment by future830759** [comment] 2018-04-20 23:37
twRO: [https://ro.gnjoy.com.tw/download/program_download.aspx](url)

**Comment by smallvill3** [comment] 2018-06-27 15:13
After 27 June 2018 maintenance, phRO and mRO are changing their Shield to EasyAntiCheat (EAC).
Existing players are forced to download the new client. [Link](https://roextreme.com/mysg/news/new-game-client-available-after-weekly-maintenance)

**Comment by moneyisgod** [comment] 2018-07-14 16:06
Looks like EAC uses ring0 driver, Maybe using NtApiMonitor someone can debug.
Dunno about cdclient

**Comment by kou90258** [comment] 2018-08-18 10:52
CdClient   Message Tokenizer  can refer to https://github.com/OpenKore/openkore/pull/1024

**Comment by kou90258** [comment] 2018-11-24 04:43
https://drive.google.com/open?id=1Nv2T0Po9jWG1h6ngiloScCBhU4F4CnSQ
This is the data file of cdclient system before PHRO. The .dll file is because there is a .dll file that has been modified by PHRO, but this information is no longer available after a single maintenance. Place a reference study here.

**Comment by Fadreus** [comment] 2019-10-26 07:07
#2957

**Comment by azuring247** [comment] 2020-09-29 02:27
@alisonrag KRO recently changed PROTECTION from CDCLIENT to NPROTECT. If you look at the main page of the wiki, it says that you are a CRO supporter using NPROTECT. How do I get in touch with you?

**Comment by kou90258** [comment] 2021-06-05 09:30
@alisonrag  Please close this issue. 
TwRO no longer used CdClient Shield.
https://ro.gnjoy.com.tw/notice/notice_view.aspx?id=4454
March 23, 2021 (Tuesday).
 Replace the protection program "nProtect".
※Sorry for the inconvenience caused by replacing the original protection program "Cheat Defender" in accordance with the relevant policies of the head office.

**Closed** 2021-06-05 16:08 UTC

**Comment by AriesCrack** [comment] 2021-12-20 09:12
TwRO recover CdClient Shield.
And openkore can not work on TWRO.

Could reopen issue?
