### ISSUE TITLE
New Server Asgard: packet tokenizer error, can't connect

### ISSUE THREAD

**Issue by zzwilzz** [OpenKore/openkore#222] opened 2016-09-14 02:29 UTC
Hi All,

There is anyone know how to fix packet tokenizer error in idRO new Asgard Server? When connecting to the Asgard Server then packet tokenizer: unknown switch: 219e appear and can't login. 

There is anyone will update the Openkore for idRO Asgard Server? Please help T_T

Thank you in advance

**Comment by Cozzie** [comment] 2016-09-15 18:30
@cydh

**Comment by cydh** [comment] 2016-09-15 22:46
1. See #77
  2. Please search before posting
  3. Don't create new issue for same matter

I don't play Asgard, I don't even bother to try to.
I don't hack Asgard encryption, I don't even bother to try to.
There are bunch of scumbags who know how to do it but keep themselves while OpenKore share everything for free. I'm not one of those scumbags :P

**Comment by itsrachelfish** [comment] 2017-01-16 18:49
Duplicate of #77 as @cydh mentioned.

**Closed by itsrachelfish** 2017-01-16 18:49 UTC
Labels: duplicate
