### ISSUE TITLE
teleportAuto_allPlayers 2 teleportAuto_notPlayers "nickname" Not Working

### ISSUE THREAD

**Issue by DSRUS** [OpenKore/openkore#3308] opened 2020-11-29 16:42 UTC
## ------------------ Openkore Issues Template ------------------

* **Openkore version git**: 

* **Server**: 

* **Bug Report / Feature Request**:

* **Summary**:

teleportAuto_allPlayers 2 ( teleport away from everyone, except the party members)
teleportAuto_notPlayers "nickname" - Not Working
But:
teleportAuto_allPlayers 1 ( teleport away from everyone )
teleportAuto_notPlayers "nickname" - Working, the bot does not teleport from the specified character

how to fix it, so that when teleportAuto_allPlayers 2 the bot did not teleport from the specified characters? sorry about Google translate))

**Comment by hubertyang88** [comment] 2020-12-16 16:59
it seems to be a bug cause by the sever, when bot see a player for the first time , some player's info is missing such as name,guild,party,  and then bot will treat this player as non party member to trigger tele , after few moments , server will send full player's info , then teleportAuto works . add a timeout to this function might help.

**Comment by hubertyang88** [comment] 2021-01-24 02:51
# skip this person if we dont know the name
next if (!defined $player->{name});

this code found in sub avoidGM_near in misc.pm seems not working , OP will take UID as player's name , this might cause some problems , when OP doesn't know the name , it don't know the party and guild name too . OP will treat this player as non party or guild player.

**Comment by alisonrag** [comment] 2021-04-26 18:56
cant reproduce in RMS

![image](https://user-images.githubusercontent.com/10372732/116135567-a8ff8780-a6a7-11eb-9a3d-4f405f69c50f.png)


openkore only teleport after i leave the party.

tested after teleport, login and moving toward to the openkore

can you give us more information about server? maybe the party handler is saving wrong informations or maybe actor ahndler is saving wrong ID

**Comment by hubertyang88** [comment] 2021-04-28 23:22
After some server updates , I can't reproduce the bug ,  log or moving into the sight of OP  ,  player's name is showed correctly  ,  . So I guess this problem  is caused by sever setting . 
BTW , I download the latest version to test , but op can't move  ,  I use the original config.txt come with  latest version , what might be the problem?

**Comment by alisonrag** [comment] 2021-04-29 01:26
> After some server updates , I can't reproduce the bug , log or moving into the sight of OP , player's name is showed correctly , . So I guess this problem is caused by sever setting .
> BTW , I download the latest version to test , but op can't move , I use the original config.txt come with latest version , what might be the problem?

i will close this related to teleport players.
can you open a new issue and give to us all the details (server, openkore version and the issue)?

**Closed by alisonrag** 2021-04-29 01:26 UTC
Labels: feature request
