### ISSUE TITLE
Timout on Character server, kRO_RagexeRE_2015_11_04a

### ISSUE THREAD

**Issue by rrrahl** [OpenKore/openkore#533] opened 2017-04-03 17:18 UTC
Hi there, i'm having an issue with a server using kRO_RagexeRE_2015_11_04a as serverType. I hope you guys can help me out. Also i couldn't extract recvpackets.txt as the launcher is over 14mo. Also the server has no protections.

server.txt:
ip 209.58.164.87
port 56384
master_version 1
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
charBlockSize 144
clientHash 09C5BFC89B1C75903942677C50D3E5B9
addTableFolders pserver;translated;translated/kRO_english;kRO

I hope you guys can  help me out ^^

**Comment by m3kgin3er** [comment] 2017-04-06 13:21
http://forums.openkore.com/viewtopic.php?f=6&t=211637

**Comment by rrrahl** [comment] 2017-04-08 04:48
I mentionned that i couldn't extract the packer because the .exe is too heavy (over 14mb), is RE, i get an error when i try to extract. Could you help ?

**Comment by m3kgin3er** [comment] 2017-04-10 02:28
https://pastebin.com/zKFpBY63

**Comment by rrrahl** [comment] 2017-04-11 16:20
I'll try the recvpacket on pastebin and take a look at the referrenced topics. I keep you updated :)

**Comment by rrrahl** [comment] 2017-04-11 16:29
Hey i just tried it out and i have the exact same error as @Razalka at #497

**Comment by m3kgin3er** [comment] 2017-04-12 08:28
Try again bro. If solved close the thread.

**Comment by rrrahl** [comment] 2017-04-12 14:08
Still the same result, i'm using the Packet keys. Should i try with https://github.com/m3kgin3er/openkore-rakkiRO-at-least ?

**Comment by Razalka** [comment] 2017-04-12 14:44
@rrrahl try it, latest fork from @m3kgin3er

**Comment by rrrahl** [comment] 2017-04-12 17:05
@Razalka Ok mate i'll, hopefully i'll get some results :)

**Comment by rrrahl** [comment] 2017-04-12 20:38
@m3kgin3er 
I've tried with openkore rakkiRO, not working i get Packet Tokenizer: Unknown Switch: 082D. and then disconnection. Just like first post's screenshot.
Any idea ? x)

**Comment by m3kgin3er** [comment] 2017-04-13 02:33
Extract the recvpackets ! will work ! Maybe

**Comment by Razalka** [comment] 2017-04-13 04:55
@rrrahl 
Try this recvpackets.
[recvpackets.txt](https://github.com/OpenKore/openkore/files/918519/recvpackets.txt)

**Comment by apuk321** [comment] 2017-04-14 05:03
ada yang bisa membantu saya dapat error 09A0
ip 128.199.220.196
port 6900
private 1
master_version 25
version 46
serverType kRO_RagexeRE_2012_04_10a
serverEncoding Western
charBlockSize 144
chatLangCode 1
addTableFolders eA;kRO/RagexeRE_2012_04_10a;translated/kRO_english;kRO
recvpackets recvpackets.txt

**Comment by rrrahl** [comment] 2017-04-15 16:17
@Razalka 
I just tried with your recvpacket.txt, still Packet Tokenizer 082D

@m3kgin3er 
I couldn't extract the recvpacket from .exe, its too heavy gives me error.

The server is AnkRO : ank-ro.com
In case somebody is willing to try directly.

Hope you guys can help me out x)

**Comment by m3kgin3er** [comment] 2017-04-17 07:51
Well i just wanna know how do you came to this topic ? 

Have u concluded, or followed the connectivity guide to get the correct sT for your server ? 
How u know if it's 2015 sT ?

**Comment by rrrahl** [comment] 2017-04-19 02:34
Of course i followed the connectivity guide, as for the sT i found it with PEViewer

**Comment by m3kgin3er** [comment] 2017-04-19 03:42
My broda post your main exe of your server!

**Comment by m3kgin3er** [comment] 2017-04-19 03:48
Man i've extracted all the packets of your server.
Then you receive that warn. If you don't have extracted the packets, i believe you don't have the keys, or enabled that listed by the default . You're using the plugin containing what keys ?

**Comment by tupaclol** [comment] 2017-04-21 07:51
Help,

Server denied conection.

[ReburnRO]
ip 63.143.54.78
port 6900
version 16
master_version 22
serverType kRO_RagexeRE_2015_11_04a
charBlockSize 147
recvpackets private.txt
addTableFolders Translated\kRO_english;kRO

**Comment by rrrahl** [comment] 2017-04-22 00:54
@m3kgin3er 
Connectivity info:
ip 209.58.164.87
port 56384
master_version 1
version 55
serverType kRO_RagexeRE_2015_11_04a
serverEncoding Western
charBlockSize 144
clientHash 09C5BFC89B1C75903942677C50D3E5B9
addTableFolders pserver;translated;translated/kRO_english;kRO

Server: ank-ro.com
Main .exe of server: https://www.mediafire.com/?284rdtp46h4uiu9

I got keys by extracting PacketLenghts, for the recvpackets i used those you told me to use on this topic.
[Packet_Keys]
1 = 0x3EB1F359
2 = 0x1D2E6FFA
3 = 0x4AFA6E3E

ht.txt : 0x3EB1F359, 0x4AFA6E3E, 0x1D2E6FFA

Sorry for the late reply, and thank you for trying to help :)

**Comment by m3kgin3er** [comment] 2017-04-22 02:51
Well. You don't need to revert the order at now. I've edited my plugin.

Put this in xh.txt :

[Packet_Keys]
1 = 0x3EB1F359
2 = 0x1D2E6FFA
3 = 0x4AFA6E3E

And use my new plugin in forum. http://forums.openkore.com/viewtopic.php?f=6&t=211637&p=274647#p274647

**Comment by rrrahl** [comment] 2017-04-22 04:34
@m3kgin3er 
I did what you said and im using "openkore-rakkiRO-at-least-master" with recvpacket https://pastebin.com/zKFpBY63 you gave me. I get now "Packet Tokenizer: Unknown switch: 082D".
Any  way to fix that ? it disconnect me

**Comment by m3kgin3er** [comment] 2017-04-22 23:01
Add one line above the addTableFolders :

recvpackets default.txt

Copy my recvp and paste into notepad and save such as default.txt ^^ save in your tables folder. Its not hard

**Comment by rrrahl** [comment] 2017-04-23 01:13
I did it and got this:
<a href="http://www.noelshack.com/2017-15-1491928915-sans-titre1.png"><img src="http://image.noelshack.com/minis/2017/15/1491928915-sans-titre1.png" border="0" alt="1491928915-sans-titre1.png - envoi d'image avec NoelShack" title="1491928915-sans-titre1.png"/></a>

The error message is:
'x' outside of string in unpack at src/Network/PacketParser.pm line 248

**Comment by m3kgin3er** [comment] 2017-04-23 04:13
Download my plugin again ! This is the old version of plugin ^^

**Comment by rrrahl** [comment] 2017-04-23 05:25
I redownloaded https://github.com/m3kgin3er/openkore-rakkiRO-at-least as you said but still no change, same error

**Comment by m3kgin3er** [comment] 2017-04-23 05:43
WoW it's a big problem.

Post the link of the server.

**Comment by rrrahl** [comment] 2017-04-23 20:49
@m3kgin3er 
Here it is: ank-ro.com

I dont understand why it doesn't work x)

**Comment by rrrahl** [comment] 2017-04-27 13:02
@m3kgin3er 
Hey, did you find a way to make it work ? Please dont give up on me :)

**Comment by m3kgin3er** [comment] 2017-04-28 21:39
I'm login inside this server now. I'll check

**Comment by rrrahl** [comment] 2017-04-28 22:11
Awesome, hopefully you'll succeed

**Comment by m3kgin3er** [comment] 2017-04-28 23:30
I was inside. Now i can't enter because of the keys ¢¢ same error at you

**Comment by rrrahl** [comment] 2017-04-29 00:59
So you think its unbotable ?

**Comment by rrrahl** [comment] 2017-04-29 01:57
Ok sure :D tell me when you're back i'll give you the item. Btw can you remove the chat ? i'd prefer if everybody in server isn't aware of openkore

**Comment by rrrahl** [comment] 2017-04-29 02:28
@m3kgin3er 
I have done what you said exactly, i can chose my character (for the first time) but i got "The server has denied your connection."


Received character ID and Map IP from Character Server
----------Game Info----------
Char ID:  ***********
MAP Name: prontera.gat
MAP IP: 116.251.223.145
MAP Port: 56677
-----------------------------
Closing connection to Character Server
Disconnecting (116.251.223.145:56547)...disconnected
Connecting to Map Server...
Connecting (116.251.223.145:56677)... connected
Sent packet    : 0360    [19 bytes]  
Disconnecting (116.251.223.145:56677)...disconnected
The server has denied your connection.

**Comment by rrrahl** [comment] 2017-04-29 02:35
Its working well done, when you done with the test, i'll close :D

**Comment by m3kgin3er** [comment] 2017-04-29 04:05
You should have problem with tele

**Comment by m3kgin3er** [comment] 2017-04-29 04:09
![image](https://cloud.githubusercontent.com/assets/12580473/25552764/6d74acb6-2c78-11e7-8eea-c7136c5dd8b3.png)

HAHAHJAHAHAHAHAHAHAHAHA THE TRUTH

**Comment by rrrahl** [comment] 2017-04-29 04:24
How to fix the teleport problem ?

**Comment by rrrahl** [comment] 2017-04-29 05:51
@m3kgin3er 
There is a huge problem, macros in macros.txt doesn't work at all. how to fix please ?

**Comment by m3kgin3er** [comment] 2017-04-29 23:32
Some peoples is experiencing errors using fly wings.
I can't reproduce this .

![image](https://cloud.githubusercontent.com/assets/12580473/25559878/f3854e30-2d1a-11e7-863c-2a473240bf6e.png)


Maybe this will not be a problem to you. Or is you having problem with teleport ?

**Comment by rrrahl** [comment] 2017-04-29 23:40
Teleport from creamy card works, so i guess fly wings too

**Comment by m3kgin3er** [comment] 2017-04-29 23:45
Can u give me one elemental weapon ? I insist. My nickname is : "SkylorD"

**Comment by rrrahl** [comment] 2017-04-30 00:59
Ok so i should change charBlockSize and try ?
If you need anything in game for your tests, tell me

**Comment by m3kgin3er** [comment] 2017-04-30 01:46
my brother i need elemental weapons. refined.

**Comment by m3kgin3er** [comment] 2017-04-30 14:50
Oh yeah nice idea my brother you can try this but at least i checked the correct is above >= 147

**Comment by LoseracK** [comment] 2017-05-01 23:48
@rrrahl won't u close this topic ? pls close;

**Comment by zackdreaver** [comment] 2017-05-05 11:13
Just wondering why it's 2015-11-04aRagexeRE, not 2015-11-04aRagexe?

The unpacked client used by PS right now is 2015-11-04aRagexe. There are no 2015-11-04aRagexeRE

**Closed** 2017-05-15 02:40 UTC

**Comment by rrrahl** [comment] 2017-05-15 03:22
@LoseracK 
Skylord; homunculus seems broke with this version, any idea how to fix it ? Or should i open a new issue ?

**Comment by LoseracK** [comment] 2017-05-15 17:23
Well. I have not understood. How it looks like "broke"?
I'm very busy but i'll see if i have time to perform some tests.

**Comment by rrrahl** [comment] 2017-05-23 01:37
@Slipxxliose 
Bro i've a problem with anti-bot.

[reactOnNPC] Conditions for reactOnNPC_0 (npc:close, rect:number) 'type' not met.
Unknown #110444922: [Bot Check]
[reactOnNPC] NPC message saved (0): "[^FFA500Bot Check^000000]".
Unknown #110444922:  
[reactOnNPC] NPC message saved (1): " ".
Unknown #110444922: What is the sum of : 14 + 4 = ?
[reactOnNPC] NPC message saved (2): "What is the sum of : ^0000FF14 + 4^000000 =^000000 ^0000FF?^000000".

reactOnNPC talk num @eval(#2~1 + #2~2) {
	type number
	delay 5
	msg_0 /[Bot Check]/
	msg_1 / /
	msg_2 /What is the sum of : (\d+) + (\d+) = ?/
}

The problem is that msg_2 doesn't match x) 

[reactOnNPC] Matching [msg (2)] "What is the sum of : 29 + 43 = ?" to "/What is the sum of : (\d+) + (\d+) = ?/" ... doesn't match.

Any idea how to fix please, would be awesome if you have a moment ^^
