### ISSUE TITLE
teleportAuto_notPlayers is not working

### ISSUE THREAD

**Issue by kittygrill** [OpenKore/openkore#153] opened 2016-07-25 08:12 UTC
Used player name as string still teleports when said player is in range

**Comment by lututui** [comment] 2016-08-19 23:39
I believe this is a logic issue in CoreLogic.pm, line 2954

`if (!existsInList($config{teleportAuto_notPlayers}, $player->{name}) **&&** !existsInList($config{teleportAuto_notPlayers}, $player->{nameID})) {`

This is only true if neither the player name nor their ID match with the configuration; meanwhile, the intended behavior is to match either one, not both.

**Comment by lututui** [comment] 2016-08-31 20:44
I can't reproduce it.

**Comment by kaliwanagan** [comment] 2017-07-09 16:22
Closing for now until repro steps are available

**Closed by kaliwanagan** 2017-07-09 16:22 UTC
Labels: bug, needs to be tested
